reilabs/lampe

- Lampe/Lampe.lean
- Lampe/Lampe/Hoare/SepTotal.lean
- Lampe/Lampe/Semantics.lean
- Lampe/Lampe/Syntax.lean
- Lampe/Lampe/Tactic/SeparationLogic.lean
This PR aims to implement the if-then-else semantics, and it closes #9.
- `Syntax.lean`: If-then-else expressions are now parsed. If no "else" body is found, then it is substituted by an `Expr.skip`.
- `Semantics.lean`: Three new `Omni` cases added: `skip`, `iteTrue`, and `iteFalse`.
- `Hoare/SepTotal.lean`: Added introduction rules `ite_intro` and `skip_intro`.
- `Tactics/SeparationLogic.lean`: Updated the `steps` tactic to handle the `ite` expressions. Added `skip_intro` to `stephelper1` and `stephelper3`.
- `Lampe.lean`: Some examples utilizing if-then-else expressions.
> If-then-else support

- Lampe/Lampe.lean
- Lampe/Lampe/Builtin/Cast.lean
- Lampe/Lampe/Builtin/Cmp.lean
- Lampe/Lampe/Hoare/Builtins.lean
- Lampe/Lampe/Syntax.lean
- Lampe/Lampe/Tactic/SeparationLogic.lean
This PR adds the `cast` builtin which makes use of the `CastTp` typeclass. The following modifications are also made at the syntax side:
- `mkBuiltin` dynamically generates the corresponding Builtin reference
- `mkStructDefIdent` introduced so that struct definitions do not collide with user definitions
- Syntax regarding to structs are updated.
> Cast builtin and syntax refinements

- Lampe/Lampe.lean
- Lampe/Lampe/Ast.lean
- Lampe/Lampe/Hoare/Builtins.lean
- Lampe/Lampe/Hoare/SepTotal.lean
- Lampe/Lampe/Hoare/Total.lean
- Lampe/Lampe/Semantics.lean
- Lampe/Lampe/SeparationLogic/SLP.lean
- Lampe/Lampe/Syntax.lean
- Lampe/Lampe/Tactic/SeparationLogic.lean
- Lampe/Lampe/Tp.lean
This PR aims to add higher order function support. 
- A new type is added `Tp.fn`
- Functions are represented by `FuncRef`s
- A new expression is added `Expr.fn` for function idents
- The call expression `Expr.call` is updated to work with a `Tp.fn`
- Call intro rules `callDecl_intro`, `callLambda_intro`, `callTrait_intro` are updated
- Syntax is updated
> Higher order functions

- Lampe/Lampe.lean
- Lampe/Lampe/Ast.lean
- Lampe/Lampe/Builtin/Basic.lean
- Lampe/Lampe/Builtin/Helpers.lean
- Lampe/Lampe/Builtin/Slice.lean
- Lampe/Lampe/Builtin/Struct.lean
- Lampe/Lampe/Data/Field.lean
- Lampe/Lampe/Data/Integers.lean
- Lampe/Lampe/Semantics.lean
- Lampe/Lampe/SeparationLogic/LawfulHeap.lean
- Lampe/Lampe/SeparationLogic/SLP.lean
- Lampe/Lampe/SeparationLogic/ValHeap.lean
- Lampe/Lampe/Syntax.lean
- Lampe/Lampe/Tp.lean
This PR minimizes the usage of `import Mathlib` and replaces it with more targeted `Mathlib` imports
I noticed some slow compilation issues (likely related to [this Zulip thread](https://leanprover.zulipchat.com/#narrow/channel/287929-mathlib4/topic/import.20Mathlib.20slows.20down.20loading)) while I was going through and first getting familiar with the library structure, and this fixes it to a certain extent.
Some downsides of this:
* There are some unexpected outcomes in downstream files when one takes away `import Mathlib`
* Certain typeclass instance/coercions were unexpectedly being used in certain places
- One in particular was `OfNat ((Fp p) × Unit) 5` which went through deducing `CommRing Unit` in 
`Lampe.Builtin.Struct` was a surprising one.
The only occurence of `import Mathlib` …
> Minimize Mathlib imports

- .github/workflows/ci.yaml
- Cargo.lock
- Cargo.toml
- README.md
- src/lean/builtin.rs
- src/lean/mod.rs
- src/lib.rs
- src/noir/project.rs
This PR updates the Noir version to `1.0.0-beta.1`, and it closes #35.
- The new Noir repository resides in https://github.com/reilabs/noir/tree/lampe-v1.0.0-beta.1. Accordingly, the CI is updated to checkout the branch `lampe-v1.0.0-beta.1`. Readme is also updated to reflect this change.
- I use `RUST_MIN_STACK_SIZE` to set the stack size of spawned threads to 16MBs, otherwise CI step `cargo test` fails.
> Update Noir version to 1.0.0-beta.1

- src/lean/mod.rs
- src/lean/pattern.rs
- src/lean/syntax.rs
- src/lib.rs
This PR aims to add pattern support. Patterns are only handled at the extractor side -- all the patterns are converted to either `let` or `let mut` bindings. 
For example, the statement 
```rust
let (mut x, y) = (1, 2)
```
is converted to
```
let param#0 = `(1, 2);
let mut x = param#0.0;
let y = param#0.1;
```
> Pattern support

- Lampe/Lampe.lean
- Lampe/Lampe/Ast.lean
- Lampe/Lampe/Data/Strings.lean
- Lampe/Lampe/Semantics.lean
- Lampe/Lampe/Syntax.lean
- Lampe/Lampe/Tactic/SeparationLogic.lean
- Lampe/Lampe/Tp.lean
- Lampe/Tests/Tests.lean
- src/lean/mod.rs
- src/lib.rs
This PR adds support for Format Strings.
So far the extractor, syntax, and type definitions are defined. Not defined is the concrete type representing format strings, and their semantics.
In the process of writing builtin support I was running into universe issues with some of the naive implementation attempts. That combined with the fact that Noir has minimal support for format strings (as far as I can intuit from my experiments), I decided to stub out the definition and get this PR ready for review sooner rather than later.
I'll make sure to add an issue for full format string semantics eventually.
> Format Strings (kind of)

- Lampe/Lampe/Syntax.lean
- src/lean/context.rs
- src/lean/mod.rs
- src/lean/pattern.rs
- src/lean/syntax.rs
- src/lib.rs
This PR aims to add `TraitAsType` support. They are handled purely at the extractor side. 
If they occur in parameter types, they are replaced by type variables. If they occur in the return type, they are replaced by the concrete type that the function body returns.
I also added a placeholder type at the Lean side, which can be invoked with `_` in the Lean definitions. This might be useful in the future.
> TraitAsType support

- Lampe/Lampe/Ast.lean
- Lampe/Lampe/Data/HList.lean
- Lampe/Lampe/Syntax.lean
- Lampe/Tests/Tests.lean
- src/lean/context.rs
- src/lean/mod.rs
- src/lean/syntax.rs
- src/lib.rs
This PR aims to extend the generics to support numerics. Most of the changes are in `Syntax.lean`.
At Lean side, generics can be declared as numeric with the `#` prefix, as shown in the following example:
```
nr_def create_arr<#N>() -> [Field; N] {
[1 : Field ; N]
}
```
> Nat generics

- Lampe/Lampe/Syntax.lean
- Lampe/Tests/Tests.lean
- src/lean/mod.rs
- src/lean/syntax.rs
- src/lib.rs
This PR aims to add type alias support, and it closes #57.
Aliases are defined using `nr_type_alias` and are referred by the `@` prefix. Under the hood, an `nr_type_alias` creates a simple `def` with a function from generics to the concrete `Tp`. In turn, a `@` prefix calls that simple `def` with the given generic arguments, which returns a `Tp`.
> Type aliases

- Lampe/Lampe/Hoare/Builtins.lean
- Lampe/Lampe/Tactic/SeparationLogic.lean
- src/lean/builtin.rs
Last couple fixes I've run into:
* Add `uShr` and `uShl` builtin support to `steps` automation.
* Fix the type signature of `uShr_intro` (this was a nasty bug to track down)
* One last builtin that's already implemented [here](https://github.com/reilabs/lampe/blob/b9f946d00b4020c29c26ba9fd2c848f26377c227/Lampe/Lampe/Builtin/Array.lean#L115-L118) but didn't get added to the list in the extractor.
> `arrayAsSlice` builtin

- src/lean/mod.rs
This PR fixes a bug in the impl block extraction in which the generic declarations (e.g., `T, U` in `impl<T, U> ...`) include concrete types. 
The following Noir code:
```rust
// ...
impl MHash<Field> for BabyHash {
// ...
}
```
would be extracted as:
```lean
nr_trait_impl[impl_405] <Field> MHash<Field> for BabyHash<> where  {
// ...
}
```
But now it correctly extracts as
```
nr_trait_impl[impl_405] <> MHash<Field> for BabyHash<> where  {
// ...
}
```
> Bug fix in impl block extraction

- Examples/Merkle/Merkle/Extracted.lean
- Lampe/Lampe/Ast.lean
- Lampe/Lampe/Hoare/SepTotal.lean
- Lampe/Lampe/Semantics.lean
- Lampe/Lampe/Syntax.lean
- Lampe/Lampe/Tactic/Steps.lean
- Lampe/Lampe/Tp.lean
- Lampe/Tests/FieldGenerics.lean
- Lampe/Tests/Tests.lean
- src/lean/builtin.rs
- src/lean/context.rs
- src/lean/mod.rs
- src/lean/pattern.rs
- src/lean/syntax.rs
- src/lib.rs
- src/noir/project.rs
This PR adds generic field elements.
Small notes associated with the PR:
* Notation for unsigned int generics was changed from just the bit-width `w` to `type_u w`
* Added notation for generic field elements as `type_fp`
* Numeric consts now have different notation depending on the type. `f@A` for `A : type_fp` and `u@B` for `B : type_u w`
* I also ran `cargo fmt` to normalize the rust formatting and prevent errant formatting diffs in future PRs (it may be worth adding this to CI in the future)
Small TODO: 
* The proof of the final lemma in `Lampe/Tests/FieldGenerics.lean` is a tad bit messy (`steps` was not able to finish the proof automatically), so it may be worth looking at why.
> Field generics

- .github/workflows/ci.yaml
- rust-toolchain.toml
- src/bin/main.rs
- src/error/emit.rs
- src/lean/builtin.rs
- src/lean/context.rs
- src/lean/mod.rs
- src/lean/pattern.rs
- src/lean/syntax.rs
- src/lib.rs
- src/noir/project.rs
This PR adds `cargo fmt` and `cargo clippy` checks to CI, and fixes all of the raised issues.
It also fixes the rust toolchain.
> Rust cleanup

- Examples/Merkle/lampe/Merkle-0.0.0/Spec.lean
- Examples/MerkleFromScratch/user_files/Spec.lean
- Examples/MerkleFromScratch/user_files/append_to_Merkle.lean
- Lampe/Lampe/Tactic/Steps.lean
- Lampe/Tests/FieldGenerics.lean
- Lampe/Tests/Negatives.lean
This PR factors out the `simp only` change to `enter_decl` and `enter_trait` from #99 to keep that PR entirely focused on the delaborator/syntax.
All the fixes in `Examples/*` and `Lampe/Tests/*` are due to the two `simp only` calls added in `Lampe/Tactic/Steps.lean`
> add `simp only` call to `enter_decl` and `enter_trait`

- Lampe/Lampe.lean
- Lampe/Lampe/Data/Meta.lean
- Lampe/Lampe/Delab.lean
- Lampe/Lampe/Tp.lean
This PR adds a delaborator for `Tp.denote`. This is part of a long effort to make the proof states
the user will encounter less "scary".
> Delaborate `Tp.denote`

- Lampe/Lampe/Builtin/Field.lean
- Lampe/Lampe/Hoare/Builtins.lean
- Lampe/Lampe/Tactic/Steps.lean
Previously these conversions (`uAsField` and `iAsField`) used `sorry` as we had not clarified the expected semantics of these conversions with Aztec. We now have clarity on how these should behave, and have implemented the correct conversion behavior in our builtins. The exact semantics of these conversions are documented in the doc blocks.
This commit adds the intro theorems for `uAsField` and `iAsField`, and also removes an incidental example that should not have been in the codebase.
Closes #44
> Fix the integer -> field element conversions

- Examples/test.sh
This PR addresses #103.
The new logic doesn't run for the two tests `TestDep` and `MerkleFromScratch` as these tests don't have checked out extracted files.
> Check file diffs in test script

- src/bin/main.rs
When relative path is being used for the project noir has some bug and relative path is joined twice. Example: `./testing/Merkle/teting/Merkle/src/main.nr`. Then compiler can't find proper files. Nargo is using absolute path so instead of fixing the bug we can follow their approach.
> Fix handling --root param.

- Lampe/Lampe/Builtin/Array.lean
- Lampe/Lampe/Builtin/Basic.lean
- Lampe/Lampe/Builtin/Slice.lean
- Lampe/Lampe/Hoare/Builtins.lean
- Lampe/Lampe/SeparationLogic/SLP.lean
- Lampe/Lampe/Tactic/Steps.lean
- Lampe/Tests/LenBuiltin.lean
- Lampe/Tests/Syntax.lean
- stdlib/lampe/lake-manifest.json
- testing/Merkle/lampe/Merkle-0.0.0/Spec.lean
- testing/MerkleFromScratch/user_files/Spec.lean
This PR addresses #197 by adding a single `arrayLen` builtin that handles both slices and arrays.
> Change `arrayLen` builtin to handle slices as well

- Lampe/Lampe/Semantics/Env.lean
- Lampe/Lampe/Tactic/Steps.lean
- Lampe/Lampe/Tp.lean
- Lampe/Tests/Envs.lean
- Lampe/Tests/Errors.lean
- Lampe/Tests/Negatives.lean
- Lampe/Tests/Syntax.lean
- testing/Merkle/lampe/Merkle-0.0.0/Spec.lean
- testing/MerkleFromScratch/user_files/Spec.lean
This PR improves the error handling for some of our tactics, addressing #92.
* `steps` flags unkonwn supplied lemmas instead of failing silently
* `enter_block_as` and `loop_inv` flag incorrectly formatted/nonsense pre and post conditions instead of failing silently
* `enter_decl` gives a more insightful error when the declaration is not in the environment 
It also adds configuration options to `steps` with the syntax
`steps <limit> [<lemmas>] +config1 +config2 -not_config3 ...`
So far only `+strict` is detected, but it leaves open the option for more fine-grained steps behavior
TODOs:
> add some error handling to steps tactic

- Lampe/Lampe/Hoare/SepTotal.lean
- Lampe/Lampe/Tactic/SL.lean
- Lampe/Lampe/Tactic/SL/Term.lean
- Lampe/Lampe/Tactic/Steps.lean
- docs/Extracted Project Structure.md
- docs/Tips for Proving.md
- stdlib/lampe/Stdlib/Array/Mod.lean
- stdlib/lampe/Stdlib/Option.lean
- stdlib/lampe/Stdlib/Slice.lean
This commit adds statements and proofs of the remaining theorems to accompany the functionality of the `std::option::Option<T>` type. It also introduces a document that aims to collate useful tips for stating theorems and proving.
Do note that it does not contain proofs for some of the traits implemented for `Option` as these will be influenced by the "lawful" trait initiative, and hence are not worth doing at this stage.
It also adds the `unsafe` mode to both the `steps` and `sl` tactics. This allows `sl` (and uses thereof embedded in `steps`) to unify from the entire proof state instead of the state of the current goal.
This is work toward #50.
> Add the remaining theorems for `Option`
